const capitals = {
  'Florianópolis': { region: 'Sul' },
  'Porto Alegre': { region: 'Sul' },
  'Curitiba': { region: 'Sul' },
  'Campo Grande': { region: 'Centro Oeste' },
  'Brasília': { region: 'Centro Oeste' },
  'Cuiabá': { region: 'Centro Oeste' },
  'Goiânia': { region: 'Centro Oeste' },
  'São Paulo': { region: 'Sudeste' },
  'Rio de Janeiro': { region: 'Sudeste' },
  'Belo Horizonte': { region: 'Sudeste' },
  'Vitória': { region: 'Sudeste' },
  'Teresina': { region: 'Nordeste' },
  'Salvador': { region: 'Nordeste' },
  'São Luís': { region: 'Nordeste' },
  'Maceió': { region: 'Nordeste' },
  'Fortaleza': { region: 'Nordeste' },
  'Recife': { region: 'Nordeste' },
  'João Pessoa': { region: 'Nordeste' },
  'Aracaju': { region: 'Nordeste' },
  'Natal': { region: 'Nordeste' },
  'Porto Velho': { region: 'Norte' },
  'Manaus': { region: 'Norte' },
  'Rio Branco': { region: 'Norte' },
  'Macapá': { region: 'Norte' },
  'Boa Vista': { region: 'Norte' },
  'Palmas': { region: 'Norte' },
  'Belém': { region: 'Norte' },
};

module.exports = capitals;
