module.exports = [
    ['Rio Branco', 'Macapá'],
    ['Macapá', 'Manaus'],
    ['Belém', 'Porto Velho'],
    ['Boa Vista', 'Palmas'],
    ['Belém', 'Rio Branco'],
    ['Palmas', 'Rio Branco'],
    ['Boa Vista', 'Salvador'],
    ['Maceió', 'Fortaleza'],
    ['São Luís', 'Salvador'],
    ['João Pessoa', 'Recife'],
    ['Recife', 'Teresina'],
    ['Teresina', 'Natal'],
    ['Aracaju', 'Salvador'],
    ['Natal', 'Aracaju'],
    ['Goiânia', 'Cuiabá'],
    ['Cuiabá', 'Campo Grande'],
    ['Campo Grande', 'Brasília'],
    ['Vitória', 'Cuiabá'],
    ['Vitória', 'Belo Horizonte'],
    ['Belo Horizonte', 'São Paulo'],
    ['São Paulo', 'Rio de Janeiro'],
    ['Rio de Janeiro', 'Curitiba'],
    ['Curitiba', 'Florianópolis'],
    ['Florianópolis', 'Porto Alegre'],
  ];
